apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: training-model-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-10-25T20:32:26.879528',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Training model", "inputs":
      [{"name": "image"}], "name": "Training model"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: training-model
  templates:
  - name: train-model
    container:
      command: [python3, main.py, ' > out.txt']
      image: '{{inputs.parameters.image}}'
      imagePullPolicy: Always
      resources:
        limits: {cpu: 12000m, memory: 16Gi, nvidia.com/gpu: 1}
        requests: {cpu: 12000m, memory: 16Gi}
    inputs:
      parameters:
      - {name: image}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: training-model
    inputs:
      parameters:
      - {name: image}
    dag:
      tasks:
      - name: train-model
        template: train-model
        arguments:
          parameters:
          - {name: image, value: '{{inputs.parameters.image}}'}
  arguments:
    parameters:
    - {name: image}
  serviceAccountName: pipeline-runner
  imagePullSecrets:
  - {name: dockerhub-private}
