_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.5
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.5
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 512
cuda:
    value: 0
dataset:
    value: kiba
edge_dropout_rate:
    value: 0
epochs:
    value: 10
gpus:
    value: "0"
lam:
    value: 0.5
lr:
    value: 0.0002
mode:
    value: test
num_pos:
    value: 10
pos_threshold:
    value: 8
seed:
    value: 2024
tau:
    value: 0.8
